[package]
name = "migration"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.13", features = ["sqlx-sqlite", "runtime-tokio", "macros"] }
sea-orm-migration = "1.1.13"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
